name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust 1.89
        run: rustup toolchain install 1.89

      - name: Build
        run: cargo +1.89.0 build --release

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: nnd
          path: target/release/nnd
